# Generated by Django 4.2.4 on 2023-08-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'компоненты',
            },
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='composition',
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='height',
            field=models.IntegerField(verbose_name='Высота в сантиметрах'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='width',
            field=models.IntegerField(verbose_name='Ширина в сантиметрах'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='composition',
            field=models.ManyToManyField(to='flower_app.composition'),
        ),
    ]
