# Generated by Django 4.2.4 on 2023-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0002_composition_remove_bouquet_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Повод')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='categories',
            field=models.ManyToManyField(related_name='bouquets', to='flower_app.category', verbose_name='Для каких поводов'),
        ),
    ]
