# Generated by Django 4.2.4 on 2023-08-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0004_alter_category_options_alter_bouquet_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес доставки'),
        ),
        migrations.CreateModel(
            name='CompositionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_app.bouquet')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_app.composition')),
            ],
        ),
    ]
