# Generated by Django 4.2.4 on 2023-08-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0005_alter_bouquet_description_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='flower_app.bouquet', verbose_name='Букет'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, choices=[('ASAP', 'Как можно скорее'), ('FROM_10_TO_12', 'С 10:00 до 12:00'), ('FROM_12_TO_14', 'С 12:00 до 14:00'), ('FROM_14_TO_16', 'С 14:00 до 16:00'), ('FROM_16_TO_18', 'С 16:00 до 18:00'), ('FROM_18_TO_20', 'С 18:00 до 20:00')], max_length=50, null=True, verbose_name='Время доставки'),
        ),
    ]
